name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: 1.x

      - name: Install Velociraptor
        run: |
          deno install -qA -n vr https://deno.land/x/velociraptor@1.0.0-beta.14/cli.ts
          echo "::add-path::$HOME/.deno/bin"

      - name: Build
        run: vr build

      - name: Test
        run: vr test
