name: Publish Egg

on:
  release:
    types: [created]

jobs:
  publish-egg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2
        with:
          deno-version: 1.x

      - name: Setup eggs CLI
        run: |
          deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.2.3/mod.ts
          echo "::add-path::$HOME/.deno/bin"

      - name: Publish Egg to Nest.land
        run: |
          eggs link --key ${NEST_LAND_API_KEY}
          eggs publish
        env:
          NEST_LAND_API_KEY: ${{secrets.NEST_LAND_API_KEY}}
